name: Tanishq Jasoria
description: Manners Maketh Man
meta_description: "I am a Senior Undergraduate student at the Department 
                   of Mathematics, IIT Kharagpur pursuing my Bachelor’s 
                   and Master’s degree in Mathematics and Computing."
meta_tags: "tanishq, jasoria, iit, kharagpur, systems, security, network
            secure system development"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap
    - jekyll-paginate

paginate: 20
domain_name: 'tanishqjasoria.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

#social-icons
facebook: tanishqjasoria
twitter: jasoriatanishq
instagram: tanishqjasoria
linkedin: tanishqjasoria
github: tanishqjasoria
email: jasoriatanishq@gmail.com

# Details for the RSS feed generator
url:            'https://tanishqjasoria.github.io'
author:         'Tanishq Jasoria'
authorTwitter:  'jasoriatanishq'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
